services:
  # Layanan Aplikasi Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_app_laravel
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - movie-network

  # Layanan Web Server Nginx
  nginx:
    image: nginx:alpine
    container_name: movie_app_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - movie-network

  # Layanan Database PostgreSQL
  db:
    image: postgres:15
    container_name: movie_app_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: movie_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - movie-network

networks:
  movie-network:
    driver: bridge

volumes:
  pgdata:
