
services:
  # LARAVEL APP (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_app_laravel
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./public/build:/var/www/html/public/build # ⬅️ Tambahkan ini
    networks:
      - movie-network

  # VITE FRONTEND SERVER
  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    container_name: movie_app_vite
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173" # Port dev server Vite
    networks:
      - movie-network

  # DATABASE POSTGRESQL
  db:
    image: postgres:15
    container_name: movie_app_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: movie_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - movie-network

  # NGINX PROXY UNTUK APLIKASI
  nginx:
    image: nginx:alpine
    container_name: movie_app_nginx
    restart: unless-stopped
    ports:
      - "8000:80" # Laravel akan bisa diakses di http://localhost:8000
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - movie-network

volumes:
  pgdata:

networks:
  movie-network:
    driver: bridge
